---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: zookeeper-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - '*'
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters/finalizers
  verbs:
  - update
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters/status
  verbs:
  - get
  - patch
  - update
