# permissions for end users to view zookeeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zookeepercluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zookeeper-operator
    app.kubernetes.io/part-of: zookeeper-operator
    app.kubernetes.io/managed-by: kustomize
  name: zookeepercluster-viewer-role
rules:
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters/status
  verbs:
  - get
