# permissions for end users to edit zookeeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/managed-by: kustomize
  name: zookeepercluster-editor-role
rules:
- apiGroups:
  - qilitang.top
  resources:
  - zookeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qilitang.top
  resources:
  - zookeeperclusters/status
  verbs:
  - get
