---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeper-operator
rules:
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters/finalizers
  verbs:
  - update
- apiGroups:
  - zookeeper.qilitang.top
  resources:
  - zookeeperclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
  verbs:
    - '*'
- apiGroups:
    - apps
  resources:
    - statefulsets
    - replicasets
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - create
