apiVersion: zookeeper.qilitang.top/v1
kind: ZookeeperCluster
metadata:
  labels:
    app.kubernetes.io/name: zookeepercluster
    app.kubernetes.io/instance: zookeepercluster-sample
    app.kubernetes.io/part-of: zookeeper-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zookeeper-operator
  name: zk2
spec:
  replicas: 3
  image: "registry.cn-hangzhou.aliyuncs.com/squids/zookeeper:3.5.10"
  config:
    initLimit: 2000
    tickTime: 200
    syncLimit: 8000
    quorumListenOnAllIPs: true
